inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Exclude:
  - 'lib/travis/logs/services/fetch*.rb'

Metrics/LineLength:
  Max: 80
  Exclude:
  - 'spec/**/*'

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Max: 30
  Exclude:
  - 'spec/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15
