inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
  Exclude:
  - 'spec/**/*'
  - Gemfile

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Max: 30
  Exclude:
  - 'spec/**/*'
