language: ruby
rvm:
- 2.4.1
jdk: openjdk8
sudo: false
dist: trusty
cache: bundler
services:
- redis
- rabbitmq
addons:
  postgresql: 9.3
env:
  global:
  - PG_DISABLE_SSL='1'
before_install:
- gem update bundler
before_script:
- bundle exec rake setup
