language: ruby
rvm:
- jruby-9.1.5.0
- 2.3.1
jdk: openjdk8
sudo: false
dist: trusty
cache: bundler
services:
- redis
- rabbitmq
addons:
  postgresql: 9.3
env:
  global:
  - PG_DISABLE_SSL='1'
  - PGUSER='postgres'
