language: ruby
rvm:
- 2.4.1
jdk: openjdk8
sudo: false
dist: trusty
cache:
  bundler: true
  directories:
  - ${HOME}/perl5
  - ${HOME}/.cache
services:
- redis
- rabbitmq
addons:
  postgresql: 9.6
env:
  global:
  - PG_DISABLE_SSL='1'
before_install:
- script/install-sqitch
- script/install-partman
- eval "$(perl -I ~/perl5/lib/perl5/ '-Mlocal::lib')"
- gem update bundler
before_script:
- bundle exec rake setup
