language: ruby

rvm: 2.5.4

dist: xenial

cache:
  bundler: true
  directories:
  - ${HOME}/perl5
  - ${HOME}/.cache

services:
- redis
- rabbitmq

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-server-dev-9.6

before_install:
- script/install-sqitch
- script/install-partman
- eval "$(perl -I ~/perl5/lib/perl5/ '-Mlocal::lib')"

before_script:
- bundle exec rake setup

# temp env var to build a new docker image
env:
  global:
  - BUILD_DOCKER: true

stages:
- name: "Testing time"
- name: "Ship to Quay.io"
  # if: type = cron OR branch =~ /^enterprise/ OR env(BUILD_DOCKER) IS present  

jobs:
  include:
  - stage: "Testing time"
  - stage: "Ship to Quay.io"
    language: bash
    script: ./script/docker-build-and-push
